### ISSUE TITLE
Error when parsing new ESL demos

### ISSUE THREAD

**Issue by adfinlay** [akiver/CSGO-Demos-Manager#185]
When trying to parse a brand new (i.e. played yesterday) demo from the current ESL season, (e.g. [Demo](http://www.hltv.org/interfaces/download.php?demoid=25729) / [Details](http://www.hltv.org/?pageid=28&&demoid=25729)), I get "An error occured while analyzing demos. This demos may be too old.".

errors.log states: 

```
2/9/2017 1:40 PM: Attempted to read past the end of the stream.
StackTrace:
   at DemoInfo.BitStreamImpl.UnsafeBitStream.RefillBuffer()
   at DemoInfo.BitStreamImpl.UnsafeBitStream.ReadFloat()
   at DemoInfo.QAngle.Parse(IBitStream reader)
   at DemoInfo.Split.Parse(IBitStream reader)
   at DemoInfo.CommandInfo.Parse(IBitStream reader)
   at DemoInfo.DemoParser.ParseDemoPacket()
   at DemoInfo.DemoParser.ParseTick()
   at DemoInfo.DemoParser.ParseNextTick()
   at DemoInfo.DemoParser.ParseToEnd(CancellationToken token)
   at Services.Concrete.Analyzer.ValveAnalyzer.<>c__DisplayClass2_0.<AnalyzeDemoAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.Concrete.Analyzer.ValveAnalyzer.<AnalyzeDemoAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.Concrete.DemosService.<AnalyzeDemo>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manager.ViewModel.Demos.DemoListViewModel.<AnalyzeDemoAsync>d__200.MoveNext()
```

I noticed that the duration and tick rate are both 0.

Is there anything that can be done regarding parsing these?

**Comment by akiver** [comment]
Corrupted demo :/
