### ISSUE TITLE
Memory management issue when exporting demos

### ISSUE THREAD

**Issue by ReagentX** [akiver/CSGO-Demos-Manager#199]
When I export a large amount of demos I get the following error:

    3/5/2017 12:39 PM: Exception of type 'System.OutOfMemoryException' was thrown.
    StackTrace:
       at System.IO.MemoryStream.set_Capacity(Int32 value)
       at System.IO.MemoryStream.EnsureCapacity(Int32 value)
       at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
       at NPOI.OpenXml4Net.OPC.Internal.MemoryPackagePartOutputStream.Write(Byte[] b, Int32 off, Int32 len)
       at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
       at System.IO.StreamWriter.Write(String value)
       at NPOI.OpenXml4Net.Util.XmlHelper.WriteAttribute(StreamWriter sw, String attributeName, String value, Boolean writeIfBlank)
       at NPOI.OpenXmlFormats.Spreadsheet.CT_Cell.Write(StreamWriter sw, String nodeName)
       at NPOI.OpenXmlFormats.Spreadsheet.CT_Row.Write(StreamWriter sw, String nodeName)
       at NPOI.OpenXmlFormats.Spreadsheet.CT_SheetData.Write(StreamWriter sw, String nodeName)
       at NPOI.OpenXmlFormats.Spreadsheet.CT_Worksheet.Write(Stream stream)
       at NPOI.XSSF.UserModel.XSSFSheet.Write(Stream stream)
       at NPOI.XSSF.UserModel.XSSFSheet.Commit()
       at NPOI.POIXMLDocumentPart.OnSave(List`1 alreadySaved)
       at NPOI.POIXMLDocumentPart.OnSave(List`1 alreadySaved)
       at NPOI.POIXMLDocument.Write(Stream stream)
       at Services.Concrete.Excel.ExcelService.<GenerateXls>d__1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
       at Manager.ViewModel.Demos.DemoListViewModel.<<get_ExportExcelCommand>b__136_0>d.MoveNext()

**Comment by ReagentX** [comment]
If adding more RAM to my PC will fix this then I will.

**Comment by akiver** [comment]
How many demos?

**Comment by ReagentX** [comment]
More than 550 demos. Storing too much on the heap?

**Comment by Chrisly3ear** [comment]
I also recently passed the 450 demos mark and cannot export a complete list anymore.

**Comment by ReagentX** [comment]
This issue is still present in the current master branch.
