### ISSUE TITLE
An error occured while sending the share code (to csgostats.gg)

### ISSUE THREAD

**Issue by Kinc4id** [akiver/CSGO-Demos-Manager#252]
Since a couple of days I cant send any replay to csgostats.gg. Every try results in the error message "An error occured while sending the share code". I can add the share code manually at csgostats.gg with no problem.

**Comment by 0BuRner** [comment]
Can you copy/paste your logs?

**Comment by Kinc4id** [comment]
Where do I find the logs?

**Comment by roguecode** [comment]
I'm getting the same, for about 2 weeks now. This is the error:

9/21/2017 9:38 AM: An error occurred while sending the request.
StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.Concrete.ThirdParties.CsgoStatsService.<SendShareCode>d__1.MoveNext()
InnerException:
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)

Maybe csgostats only allows HTTPS now?

**Comment by Kinc4id** [comment]
Anything?

**Comment by roguecode** [comment]
Thank you!
