### ISSUE TITLE
Fix faceit analyzing

### ISSUE THREAD

**Issue by 0BuRner** [akiver/CSGO-Demos-Manager#26]
Since the last update of Faceit, it seems something in the demo file changed : the demo header seems wrong or at least has changed (duration always 00:00:00, no tick nor framerate information) and all demo are triggering error at the end of the analysis, here is stacktrace : 
```
14/06/2015 13:56: Attempted to read past the end of the stream.
StackTrace:
   at DemoInfo.BitStreamImpl.UnsafeBitStream.RefillBuffer()
   at DemoInfo.BitStreamImpl.UnsafeBitStream.ReadByte()
   at DemoInfo.DemoParser.ParseTick()
   at DemoInfo.DemoParser.ParseNextTick()
   at DemoInfo.DemoParser.ParseToEnd()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CSGO_Demos_Manager.Services.Analyzer.EbotAnalyzer.<AnalyzeDemoAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CSGO_Demos_Manager.Services.DemosService.<AnalyzeDemo>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CSGO_Demos_Manager.ViewModel.HomeViewModel.<RefreshSelectedDemos>d__159.MoveNext()
```

**Comment by 0BuRner** [comment]
Seems it was a bug with Faceit's demo files
