### ISSUE TITLE
Error when downloading demo from share code

### ISSUE THREAD

**Issue by XKCAndy** [akiver/CSGO-Demos-Manager#281]
failed trying to download a demo from share code,and i'm sure demo is not corrupted
Errors.log
2/4/2018 7:07 PM: Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
StackTrace:
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at Core.ShareCode.Decode(String shareCode)
   at Services.Concrete.SteamService.<DownloadDemoFromShareCode>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manager.ViewModel.Demos.DemoListViewModel.<<get_DownloadDemoFromShareCodeCommand>b__173_0>d.MoveNext()

**Comment by akiver** [comment]
Could send me the sharecode please?

**Comment by XKCAndy** [comment]
CSGO-RHLbz-Et4AF-HoKBr-kcmzW-FHtdA
