### ISSUE TITLE
Cant download HLAE?

### ISSUE THREAD

**Issue by punisherpain** [akiver/CSGO-Demos-Manager#289]
2/24/2018 2:08 PM: The request was aborted: Could not create SSL/TLS secure channel.
StackTrace:
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.Concrete.Movie.HlaeService.<GetLastReleaseObject>d__8.MoveNext()
-----------------------------------

**Comment by ripieces** [comment]
https://github.com/blog/2507-weak-cryptographic-standards-removed

**Comment by UFRJ-Cyfer** [comment]
I just found a workaround for this:

- simply download HLAE from the website (https://www.advancedfx.org/download/)
- place it in the data folder (%APPDATA%\Local\AkiVer\)
- change the folder name to "hlae" (I do not know if this is necessary tho) 
- copy the "version" file from the other programs folder (like ffmpeg or virtualdub) to the "hlae" folder
- (not necessary) edit the copied version file and input the correct version (2.47.3) 

this makes the csgodm recognize the hlae executable and everything works.
