### ISSUE TITLE
Cant make movie

### ISSUE THREAD

**Issue by smilezHD** [akiver/CSGO-Demos-Manager#323]
i get a loader failed and this description
```
AfxError #2001: 
Title: Loader failed.
Description: System.ApplicationException: Failed to launch program, error code: 5
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
Inner exception: System.ApplicationException: Failed to launch program, error code: 5
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
```
no solution 
anyone?

**Comment by dtugend** [comment]
Turn off AntiCheat software before using HLAE mode.

**Comment by akiver** [comment]
This is not a CSGO DM issue, check the previous comment from @dtugend.
