### ISSUE TITLE
Problem with downloading Virtualdub

### ISSUE THREAD

**Issue by Lefty1H** [akiver/CSGO-Demos-Manager#328]
From Logs:
-------------------------------
10-Jul-18 6:14 PM: The operation has timed out
StackTrace:
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Services.Concrete.Movie.VirtualDubService.<>c__DisplayClass10_2.<Download>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.Concrete.Movie.VirtualDubService.<Download>d__10.MoveNext()
-----------------------------------

**Comment by akiver** [comment]
It looks like a server or network issue, I just tested without problems.
You are maybe behind a proxy?
