### ISSUE TITLE
ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by RealBirkoff** [akiver/CSGO-Demos-Manager#33]
When starting the application, it refreshes my demo's and crashes. 

Here's the stacktrace from the Windows Event Viewer:

	Application: CSGODemosManager.exe
	Framework Version: v4.0.30319
	Description: The process was terminated due to an unhandled exception.
	Exception Info: System.ArgumentOutOfRangeException
	Stack:
	   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c__DisplayClass2.<ThrowAsync>b__3(System.Object)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
	   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
	   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
	   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
	   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
	   at System.Windows.Threading.DispatcherOperation.Invoke()
	   at System.Windows.Threading.Dispatcher.ProcessQueue()
	   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
	   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
	   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
	   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
	   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
	   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
	   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
	   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
	   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
	   at System.Windows.Application.RunDispatcher(System.Object)
	   at System.Windows.Application.RunInternal(System.Windows.Window)
	   at CSGO_Demos_Manager.App.Main()

**Comment by RealBirkoff** [comment]
Well it seems there was a 0kb demo in my demo folder due to a failed download. Can the application ignore these instead of trying to parse and throwing an exception?
