### ISSUE TITLE
Unable to install HLAE because zip file has virus or unwanted files

### ISSUE THREAD

**Issue by kukreja-vikramaditya** [akiver/CSGO-Demos-Manager#481]
HLAE installation fails and this is the error log. I tried separately installing but seems like software can't detect that yet. Version 2.13.12
```
11/15/2020 12:17 PM: Operation did not complete successfully because the file contains a virus or potentially unwanted software.

Type: System.IO.IOException
StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Services.Concrete.Movie.HlaeService.<>c__DisplayClass10_0.<ExtractArchive>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.Concrete.Movie.HlaeService.<ExtractArchive>d__10.MoveNext()
-----------------------------------
```

**Comment by hacklex** [comment]
please, give us an option to manually specify path to HLAE. Currently can't record anything :(

**Comment by CalvinGrain** [comment]
Allow it in windows security - virus and threat protection

**Comment by akiver** [comment]
I can't reproduce the issue, it looks related to your AV.
You can copy / paste the HLAE folder here `C:\Users\USERNAME\AppData\Local\AkiVer\hlae`, the app will start HLAE from this directory.
