### ISSUE TITLE
Screen loading map 100% then back to main screen

### ISSUE THREAD

**Issue by chaingoc** [akiver/CSGO-Demos-Manager#513]
```
15/03/2021 17:38: The remote server returned an error: (404) Not Found.
Type: System.Net.WebException
StackTrace:
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Services.Concrete.Movie.FFmpegService.<>c__DisplayClass10_0.<Download>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.Concrete.Movie.FFmpegService.<Download>d__10.MoveNext()
-----------------------------------
15/03/2021 17:38: The remote server returned an error: (404) Not Found.
Type: System.Net.WebException
StackTrace:
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Services.Concrete.Movie.FFmpegService.<>c__DisplayClass10_0.<Download>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.Concrete.Movie.FFmpegService.<Download>d__10.MoveNext()
-----------------------------------
15/03/2021 17:41: The remote server returned an error: (404) Not Found.
Type: System.Net.WebException
StackTrace:
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Services.Concrete.Movie.FFmpegService.<>c__DisplayClass10_0.<Download>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.Concrete.Movie.FFmpegService.<Download>d__10.MoveNext()
-----------------------------------
15/03/2021 17:41: The remote server returned an error: (404) Not Found.
Type: System.Net.WebException
StackTrace:
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Services.Concrete.Movie.FFmpegService.<>c__DisplayClass10_0.<Download>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.Concrete.Movie.FFmpegService.<Download>d__10.MoveNext()
-----------------------------------
15/03/2021 17:47: The remote server returned an error: (404) Not Found.
Type: System.Net.WebException
StackTrace:
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Services.Concrete.Movie.FFmpegService.<>c__DisplayClass10_0.<Download>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.Concrete.Movie.FFmpegService.<Download>d__10.MoveNext()
-----------------------------------
15/03/2021 23:55: The remote server returned an error: (404) Not Found.
Type: System.Net.WebException
StackTrace:
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Services.Concrete.Movie.FFmpegService.<>c__DisplayClass10_0.<Download>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.Concrete.Movie.FFmpegService.<Download>d__10.MoveNext()
-----------------------------------
16/03/2021 00:11: The remote server returned an error: (404) Not Found.
Type: System.Net.WebException
StackTrace:
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Services.Concrete.Movie.FFmpegService.<>c__DisplayClass10_0.<Download>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.Concrete.Movie.FFmpegService.<Download>d__10.MoveNext()
-----------------------------------
16/03/2021 10:32: The remote server returned an error: (404) Not Found.
Type: System.Net.WebException
StackTrace:
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Services.Concrete.Movie.FFmpegService.<>c__DisplayClass10_0.<Download>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.Concrete.Movie.FFmpegService.<Download>d__10.MoveNext()
-----------------------------------
```

**Comment by akiver** [comment]
The logs are related to the ffmpeg installation failing which will be fixed in the next version, not the playback issue.
About the game main screen issue, please read https://csgo-demo-manager.com/docs/watch#stuck-menu
