### ISSUE TITLE
Faceit demos wont work

### ISSUE THREAD

**Issue by JurajSimovic** [akiver/CSGO-Demos-Manager#516]
![Snímka obrazovky 2021-03-27 133544](https://user-images.githubusercontent.com/46939316/112762304-427f3f00-8fff-11eb-9a7f-14ad2d56106b.jpg)
So I have one old demo from faceit that works but when I try to open these new ones that I recently downloaded It just shows me this error.

**Comment by sveinnthorarins** [comment]
Same problem here, new faceit demos not working.

Here is the error log, if that helps at all:

```
4/3/2021 1:49 PM: Object reference not set to an instance of an object.
Type: System.NullReferenceException
StackTrace:
   at Manager.ViewModel.Demos.DemoDetailsViewModel.<UpdateDemoFromAppArgument>d__151.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manager.ViewModel.Demos.DemoDetailsViewModel.<<get_WindowLoaded>b__83_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
-----------------------------------
4/3/2021 1:49 PM: Object reference not set to an instance of an object.
Type: System.NullReferenceException
StackTrace:
   at Manager.ViewModel.Demos.DemoDetailsViewModel.<UpdateDemoFromAppArgument>d__151.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manager.ViewModel.Demos.DemoDetailsViewModel.<<get_WindowLoaded>b__83_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Manager.App.Main()
-----------------------------------
```

**Comment by sveinnthorarins** [comment]
Sorry, I was trying to open the .gz files FACEIT gives you. Completely forgot to extract them first. My bad. :)

**Comment by sheharyaar** [comment]
@JurajSimovic Please verify if the solution by @sveinnthorarins works for you and close the issue.

**Comment by kizercs** [comment]
Having same issue

**Comment by akiver** [comment]
Could you try with the last version please?
The error in the logs should have been fixed.
