### ISSUE TITLE
Acces is Denied when trying to watch demo and/or highlights

### ISSUE THREAD

**Issue by mconnat** [akiver/CSGO-Demos-Manager#603]
Hello !

This is the first time i'am trying to use your tool that looks awesome.

When i'am trying to watch a demo from the csgo-demos-manager app, i'am facing an error:

```
1/5/2023 7:38 PM: Access is denied
Type: System.ComponentModel.Win32Exception
StackTrace:
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Services.Concrete.GameLauncher.<StartGame>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.Concrete.GameLauncher.<WatchHighlightDemo>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Manager.ViewModel.Demos.DemoListViewModel.<ProcessWatchHighOrLow>d__201.MoveNext()
-----------------------------------
```

None of steam and csgo-demos-manager are running wth admins rights.

I'am running my computer with:

Windows 11 Pro 22H2
OS Build 22621.963

Do you already faced that case ? Do you have any ideas ?

Thank you

**Comment by mconnat** [comment]
Hello,

The solution was simple as:

I did install Steam under C:\Steam directly.
I have made a shortcut of the Steam folder under C:\Program Files (x86)\Steam

Now csgo-demo-manager can start csgo.exe without any problems.

Sorry for the noise.
